import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';
import { task } from 'ember-concurrency';
import { runTask } from 'ember-lifeline';
import type Store from 'ember-data/store';
import type IntlService from 'ember-intl/services/intl';

// eslint-disable-next-line ember/use-ember-data-rfc-395-imports
import type { DS } from 'ember-data';

import ENV from 'irene/config/environment';
import parseError from 'irene/utils/parse-error';
import type { PaginationProviderActionsArgs } from 'irene/components/ak-pagination-provider';
import type FileModel from 'irene/models/file';
import type CapturedApiModel from 'irene/models/capturedapi';
import type ApiScanService from 'irene/services/api-scan';
import type IreneAjaxService from 'irene/services/ajax';
import type { AjaxError } from 'irene/services/ajax';

export interface FileDetailsApiScanCapturedApisSignature {
  Args: {
    file: FileModel;
  };
}

type CapturedApiQueryResponse =
  DS.AdapterPopulatedRecordArray<CapturedApiModel> & {
    meta: { count: number };
  };

type SelectAPIResponse = {
  count: number;
  results: unknown[];
};

export default class FileDetailsApiScanCapturedApisComponent extends Component<FileDetailsApiScanCapturedApisSignature> {
  @service declare intl: IntlService;
  @service declare ajax: IreneAjaxService;
  @service declare store: Store;
  @service declare apiScan: ApiScanService;
  @service('notifications') declare notify: NotificationService;

  @tracked selectedCount = 0;
  @tracked allAPIsSelected = false;
  @tracked showAPIListLoadingState = true; // Manual control of loading state
  @tracked capturedApiResponse: CapturedApiQueryResponse | null = null;
  @tracked limit = 10;
  @tracked offset = 0;

  @tracked projectProfileApiFilters: string[] = [];
  @tracked autoGeneratedApiFilters: string[] = [];
  @tracked selectedAPIUrlDomain: string[] = [];

  fileEndpoint = `${ENV.endpoints['files']}/${this.args.file.id}`;

  constructor(
    owner: unknown,
    args: FileDetailsApiScanCapturedApisSignature['Args']
  ) {
    super(owner, args);

    this.initializeCapturedApiData.perform();
  }

  willDestroy(): void {
    super.willDestroy();

    this.apiScan.setFooterComponent(null, {});
  }

  get capturedApiList() {
    return this.capturedApiResponse?.slice() || [];
  }

  get selectedDomainsStr() {
    return this.selectedAPIUrlDomain.join(',');
  }

  get totalCapturedApiCount() {
    return this.capturedApiResponse?.meta?.count || 0;
  }

  get hasNoCapturedApi() {
    return this.totalCapturedApiCount === 0;
  }

  get modAllSelectedAPIsEndpoint() {
    return `${this.fileEndpoint}/toggle_captured_apis`;
  }

  get hideCapturedApiHeader() {
    return (
      this.hasNoCapturedApi &&
      this.selectedAPIUrlDomain.length === 0 &&
      !this.fetchCapturedApis.isRunning &&
      !this.selectAllCapturedApis.isRunning
    );
  }

  get noDomainFilterResults() {
    return this.hasNoCapturedApi && this.selectedAPIUrlDomain.length > 0;
  }

  get isLoadingCapturedApiData() {
    return (
      (this.fetchCapturedApis.isRunning ||
        this.selectAllCapturedApis.isRunning) &&
      this.showAPIListLoadingState
    );
  }

  setFooterComponentDetails() {
    // Don't show footer component if there are no domain filters
    if (this.noDomainFilterResults) {
      this.apiScan.setFooterComponent(null, {});

      return;
    }

    // Don't show footer component if there are no captured APIs
    if (this.hasNoCapturedApi) {
      return;
    }

    // Show and update footer component with selected and total captured APIs count
    this.apiScan.setFooterComponent(
      'file-details/api-scan/captured-apis/footer',
      {
        selectedCount: this.selectedCount,
        totalCount: this.totalCapturedApiCount,
      }
    );
  }

  @action
  handlePrevNextAction({ limit, offset }: PaginationProviderActionsArgs) {
    this.limit = limit;
    this.offset = offset;

    this.fetchCapturedApis.perform(limit, offset);
  }

  @action
  handleItemPerPageChange({ limit }: PaginationProviderActionsArgs) {
    this.limit = limit;
    this.offset = 0;
    this.limit = limit;

    this.fetchCapturedApis.perform(limit, this.offset);
  }

  @action
  getCapiToggleState(capi: CapturedApiModel) {
    return capi.isActive;
  }

  @action
  async handleSelectAllCapturedApis(_: Event, checked: boolean) {
    this.showAPIListLoadingState = false;

    await this.selectAllCapturedApis.perform(checked);
    await this.refreshCapturedApiData.perform();

    this.showAPIListLoadingState = true;
  }

  @action
  async onDomainFilterApply(domainFilters: string[]) {
    this.offset = 0;

    await this.selectAllCapturedApis.perform(
      this.allAPIsSelected,
      domainFilters
    );

    this.refreshCapturedApiData.perform();
  }

  initializeCapturedApiData = task(async () => {
    await this.getAllAPIsSelectedStatus.perform();
    await this.fetchAPIScanDomainfilters.perform();
    await this.fetchCapturedApis.perform(this.limit, this.offset);
  });

  refreshCapturedApiData = task(async () => {
    await this.fetchCapturedApis.perform(this.limit, this.offset);
  });

  getSelectedApis = task(async () => {
    const params = {
      fileId: this.args.file.id,
      is_active: 'true',
      domains: this.selectedDomainsStr,
    };

    const queryParams = new URLSearchParams(params).toString();
    const url = `${this.fileEndpoint}/capturedapis`;
    const fullUrl = `${url}?${queryParams}`;

    return await this.ajax.request<SelectAPIResponse>(fullUrl, {
      namespace: ENV.namespace_v2,
    });
  });

  fetchAndSetSelectedApiCount = task(async () => {
    try {
      const selectedApis = await this.getSelectedApis.perform();

      if (selectedApis) {
        this.selectedCount = selectedApis.count;
      }

      this.setFooterComponentDetails();
    } catch (error) {
      const err = error as AjaxError;
      this.notify.error(err.toString());
    }
  });

  toggleApi = task(async (capturedApi: CapturedApiModel) => {
    try {
      capturedApi.set('isActive', !capturedApi.isActive);
      await capturedApi.save();

      this.notify.success(this.intl.t('capturedApiSaveSuccessMsg'));

      this.showAPIListLoadingState = false;

      await this.fetchAndSetSelectedApiCount.perform();
      await this.getAllAPIsSelectedStatus.perform();
    } catch (err) {
      // Necessary to prevent the checkbox's two-way binding to revert the captured API state after toggling
      // Two-way bindings try to keep the status in sync, but when the checkbox "checked" state changes state in the same event cycle that the DOM changed,
      // race conditions or the binding system might not properly update the DOM.
      runTask(this, () => capturedApi.rollbackAttributes());

      this.notify.error(parseError(err, this.intl.t('tPleaseTryAgain')));
    } finally {
      this.showAPIListLoadingState = true;
    }
  });

  selectAllCapturedApis = task(
    async (selectedAllAPIs: boolean, domainFilters?: string[]) => {
      this.selectedAPIUrlDomain = domainFilters ?? this.selectedAPIUrlDomain;

      try {
        await this.ajax.put(this.modAllSelectedAPIsEndpoint, {
          data: {
            is_active: selectedAllAPIs,
            domains: this.selectedAPIUrlDomain,
          },
          namespace: ENV.namespace_v2,
        });
      } catch (err) {
        this.notify.error(parseError(err, this.intl.t('pleaseTryAgain')));
      }
    }
  );

  getAllAPIsSelectedStatus = task(async () => {
    const queryParams = new URLSearchParams({
      domains: this.selectedDomainsStr,
    }).toString();

    try {
      const allAPIsSelected = await this.ajax.request<{ is_active: boolean }>(
        `${this.modAllSelectedAPIsEndpoint}?${queryParams}`,
        { namespace: ENV.namespace_v2 }
      );

      this.allAPIsSelected = allAPIsSelected.is_active;
    } catch (err) {
      this.notify.error(parseError(err, this.intl.t('pleaseTryAgain')));
    }
  });

  fetchAPIScanDomainfilters = task(async () => {
    try {
      const filtersListURL = `${this.fileEndpoint}/capturedapis_domains`;

      const res = await this.ajax.request<{
        project_profile_api_filters: string[];
        auto_generated_api_filters: string[];
      }>(filtersListURL, { namespace: ENV.namespace_v2 });

      this.projectProfileApiFilters = res.project_profile_api_filters;
      this.autoGeneratedApiFilters = res.auto_generated_api_filters;
    } catch (error) {
      this.notify.error(parseError(error, this.intl.t('pleaseTryAgain')));
    }
  });

  fetchCapturedApis = task(async (limit: number, offset: number) => {
    try {
      this.capturedApiResponse = (await this.store.query('capturedapi', {
        limit,
        offset,
        fileId: this.args.file.id,
        domains: this.selectedDomainsStr,
      })) as CapturedApiQueryResponse;

      this.fetchAndSetSelectedApiCount.perform();
    } catch (error) {
      const err = error as AdapterError;
      this.notify.error(err.toString());
    }
  });
}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'FileDetails::ApiScan::CapturedApis': typeof FileDetailsApiScanCapturedApisComponent;
    'file-details/api-scan/captured-apis': typeof FileDetailsApiScanCapturedApisComponent;
  }
}
