export const MaterialSymbolsSet = [
  'add',
  'content-copy',
  'content-copy-outline',
  'delete',
  'delete-outline',
  'done',
  'security',
  'arrow-drop-down',
  'arrow-drop-up',
  'group',
  'close',
  'edit',
  'note-add',
  'refresh',
  'arrow-left',
  'arrow-right',
  'folder',
  'folder-outline',
  'graphic-eq',
  'inventory-2',
  'account-box',
  'account-balance',
  'credit-card',
  'credit-card-outline',
  'groups-2',
  'groups',
  'west',
  'warning',
  'arrow-back',
  'search',
  'check-circle',
  'cancel',
  'more-vert',
  'group-add',
  'integration-instructions',
  'verified',
  'subdirectory-arrow-right',
  'download',
  'settings',
  'settings-applications',
  'person-remove',
  'remove',
  'file-upload',
  'event',
  'assignment',
  'notifications',
  'dynamic-feed',
  'cloud-upload',
  'import-contacts',
  'support',
  'account-circle',
  'mail',
  'logout',
  'open-in-new',
  'view-list',
  'receipt-long',
  'history-toggle-off',
  'trending-up',
  'view-stream',
  'trending-down',
  'info',
  'block',
  'help',
  'description',
  'description-outline',
  'draft-outline',
  'compare-arrows',
  'format-list-bulleted',
  'play-arrow',
  'stop',
  'build',
  'person-off',
  'person-off-outline',
  'person-add',
  'person',
  'person-outline',
  'error',
  'undo',
  'arrow-down',
  'keyboard-backspace',
  'keyboard-return',
  'south',
  'east',
  'menu',
  'sync-alt',
  'home',
  'android',
  'windows',
  'mobile',
  'lock',
  'circle',
  'circle-outline',
  'timer',
  'timer-outline',
  'drag-handle',
  'remove-circle',
  'text-snippet',
  'text-snippet-outline',
  'schedule',
  'key',
  'arrow-forward',
  'calendar-month',
  'content-paste',
  'email',
  'send',
  'chevron-left',
  'chevron-right',
  'double-arrow-left',
  'double-arrow-right',
  'apps',
  'compare',
  'shape-line',
  'check',
  'article',
  'link',
  'show-chart',
  'downloading',
  'download-done',
  'desktop-windows',
  'visibility',
  'visibility-off',
  'lock-open',
  'lock-open-outline',
  'chat-bubble',
  'keyboard-tab',
  'date-range',
  'filter-list',
  'sort',
  'wb-incandescent',
  'drive-file-rename-outline',
  'event-note',
  'open-in-full',
  'bug-report',
  'expand-more',
  'verified-user',
  'auto-fix-high',
  'do-not-disturb-on',
  'do-not-disturb-on-outline',
  'stop-circle',
  'location-searching',
  'auto-graph',
  'north-east',
  'schedule-send',
  'add-box',
  'account-tree',
  'unfold-less',
  'unfold-more',
  'arrow-downward',
  'arrow-upward',
  'archive',
  'unarchive',
  'report',
  'arrow-outward',
  'beenhere',
  'network-intel-node',
  'auto-awesome',
  'auto-awesome-outline',
  'reorder',
  'unarchive',
  'license-outline-rounded',
  'shield',
  'shield-outline',
  'indeterminate-check-box',
  'supervisor-account',
  'supervisor-account-outline',
  'language',
  'replay',
  'add-column-right-outline-rounded',
  'cards-sharp',
] as const;

export const MdiIconsSet = [
  'checkbox-marked',
  'checkbox-blank-outline',
  'insert-drive-file',
  'radio-button-checked',
  'radio-button-unchecked',
  'microsoft-excel',
  'minus-box',
  'report-problem',
  'wand',
  'progress-clock',
] as const;

export const HugeIconsSet = ['api', 'ai-brain-04'] as const;

export const FaBrandsIconsSet = ['apple'] as const;

export const IcIconsSet = ['outline-drive-file-rename-outline'] as const;

export const BxIconsSet = ['mobile-alt'] as const;

export const PhIconsSet = ['diamonds-four'] as const;

export const MynauiIconsSet = ['frame'] as const;

export const SolarIconsSet = ['library-linear'] as const;
