name: Setup App
description: Setup Application
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install npm v10
      shell: bash
      run: npm install -g npm@10

    - name: Cache dependencies
      id: cacheStep
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      if: steps.cacheStep.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
