import Component from '@glimmer/component';
import { service } from '@ember/service';
import { action } from '@ember/object';
import type IntlService from 'ember-intl/services/intl';
import type { FileDetailsApiScanCapturedApisApiDomainFiltersExtra } from '../index';

interface FileDetailsApiScanCapturedApisApiDomainFiltersGroupOptionArgs {
  Args: {
    extra?: FileDetailsApiScanCapturedApisApiDomainFiltersExtra;
    group: {
      id: string;
      groupName: string;
      options: string[];
    };
  };
}

export default class FileDetailsApiScanCapturedApisApiDomainFiltersGroupOptionComponent extends Component<FileDetailsApiScanCapturedApisApiDomainFiltersGroupOptionArgs> {
  @service declare intl: IntlService;

  get beforeOptionLabel() {
    return this.args.extra?.beforeOptionLabel;
  }

  get fileProjectId() {
    return this.args.extra?.file.project.get('id');
  }

  get isProjectProfileFilters() {
    return this.args.group.id === 'project-profile-filters';
  }

  get noDomainFilterResultsText() {
    if (this.isProjectProfileFilters) {
      return this.intl.t('apiScanModule.noProjectProfileFilters');
    }

    return this.intl.t('apiScanModule.noAutoGeneratedFilters');
  }

  @action
  isDomainFilterSelected(option: string) {
    return this.args.extra?.isDomainFilterSelected(option);
  }

  @action
  onSelectAPIUrlDomainChange(option: string) {
    this.args.extra?.onSelectAPIUrlDomainChange(option);
  }
}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'file-details/api-scan/captured-apis/api-domain-filters/group-option': typeof FileDetailsApiScanCapturedApisApiDomainFiltersGroupOptionComponent;
  }
}
