export const DYNAMIC_SCAN_STATUS = {
  NOT_STARTED: 0,
  PREPROCESSING: 1,
  PROCESSING_SCAN_REQUEST: 2,
  IN_QUEUE: 3,
  DEVICE_ALLOCATED: 4,
  CONNECTING_TO_DEVICE: 5,
  PREPARING_DEVICE: 6,
  INSTALLING: 7,
  CONFIGURING_API_CAPTURE: 8,
  HOOKING: 9,
  LAUNCHING: 10,
  READY_FOR_INTERACTION: 11,
  DOWNLOADING_AUTOPILOT_SCRIPT: 12,
  CONFIGURING_AUTOPILOT: 13,
  AUTOPILOT_RUNNING: 14,
  AUTOPILOT_COMPLETED: 15,
  STOP_SCAN_REQUESTED: 16,
  SCAN_TIME_LIMIT_EXCEEDED: 17,
  SHUTTING_DOWN: 18,
  CLEANING_DEVICE: 19,
  RUNTIME_DETECTION_COMPLETED: 20,
  ANALYZING: 21,
  ANALYSIS_COMPLETED: 22,
  TIMED_OUT: 23,
  ERROR: 24,
  CANCELLED: 25,
  TERMINATED: 26,
} as const;

export const SCAN_RUNNING_STATUSES: number[] = [
  DYNAMIC_SCAN_STATUS.DEVICE_ALLOCATED,
  DYNAMIC_SCAN_STATUS.CONNECTING_TO_DEVICE,
  DYNAMIC_SCAN_STATUS.PREPARING_DEVICE,
  DYNAMIC_SCAN_STATUS.INSTALLING,
  DYNAMIC_SCAN_STATUS.CONFIGURING_API_CAPTURE,
  DYNAMIC_SCAN_STATUS.HOOKING,
  DYNAMIC_SCAN_STATUS.LAUNCHING,
  DYNAMIC_SCAN_STATUS.READY_FOR_INTERACTION,
];

export const SCAN_STOPPED_STATUSES: number[] = [
  DYNAMIC_SCAN_STATUS.RUNTIME_DETECTION_COMPLETED,
  DYNAMIC_SCAN_STATUS.ANALYZING,
  DYNAMIC_SCAN_STATUS.ANALYSIS_COMPLETED,
  DYNAMIC_SCAN_STATUS.TIMED_OUT,
  DYNAMIC_SCAN_STATUS.ERROR,
  DYNAMIC_SCAN_STATUS.CANCELLED,
  DYNAMIC_SCAN_STATUS.TERMINATED,
];

export const RISK_LEVEL = {
  PASSED: 0,
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4,
} as const;
