name: Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    environment:
      name: Production
      url: https://secure.appknox.com
    concurrency:
      group: ${{ github.workflow }}-ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Application
        uses: ./.github/actions/setup-app

      - run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: 'production'
          IRENE_ENABLE_HOTJAR: 'True'
          IRENE_ENABLE_MARKETPLACE: 'True'
          IRENE_ENABLE_PENDO: 'True'
          IRENE_ENABLE_ROLLBAR: 'True'
          ROLLBAR_ACCESS_TOKEN: 'f1d76383c2d346a3aeedc21823f18c76'
