name: E2E Test
on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
  push:
    branches:
      - develop
      - main
      - master

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      deployments: write

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Application
        uses: ./.github/actions/setup-app

      - name: Cache cypress binary
        id: cacheCypressBinary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install cypress binary
        if: steps.cacheCypressBinary.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME}}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_TEST_RECORD_ID}}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_TEST_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          start: npm run startprod
          install: false
          config: pageLoadTimeout=100000
          wait-on: 'http://localhost:4200'
          record: true
          parallel: true
