name: E2E Test
on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
  push:
    branches:
      - develop
      - main
      - master

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      deployments: write

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME}}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_TEST_RECORD_ID}}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_TEST_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          start: npm run startprod
          install: false
          config: pageLoadTimeout=100000
          wait-on: 'http://localhost:4200'
          record: true
          parallel: true
